name = "Wychelean"
version = "0.1.0"
defaultTargets = ["Wychelean"]
testDriver = "knownAnswerTests"

[[require]]
name = "mathlib"
scope = "leanprover-community"

[[lean_lib]]
name = "Wychelean"

[[lean_exe]]
name = "knownAnswerTests"
root = "KnownAnswerTests.Main"
