import Wychelean.Hashes.SHA3.UpstreamTests
import Wychelean.Hashes.SHA3.Rsp
import Wychelean.Utils.Hex
import RunTests.Basic

/-!
# NIST SHA3 fixtures

Downloaded unchanged from the [NIST CAVP secure hashing page](https://csrc.nist.gov/projects/cryptographic-algorithm-validation-program/secure-hashing).
The response files were generated by CAVS 19.0 in January 2016. Length fields are in bits.
The test driver runs all 4,912 direct cases and all 800 Monte Carlo checkpoints.
Each checkpoint executes 1,000 iterations, using SHA3VS §6.2.3, not the SHA256 procedure.

Archive URLs and SHA-256 digests (digests identify the downloaded artifacts):

- [sha-3bytetestvectors.zip](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/sha3/sha-3bytetestvectors.zip): `cd07701af2e47f5cc889d642528b4bf11f8b6eb55797c7307a96828ed8d8fc8c`
- [sha-3bittestvectors.zip](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/sha3/sha-3bittestvectors.zip): `339454bb4b96e299fefcad403797523f1952462a28d2418c108aea30263643ae`

Non-byte-aligned bit strings use low bits of the final byte; unused high bits must be zero.
The parser validates encoded lengths and sequential COUNT fields.
Empty messages use NIST's `Len = 0, Msg = 00` convention.

[SHA3VS](https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/sha3/sha3vs.pdf)
§6.2.3 defines the Monte Carlo recurrence.
-/

namespace Wychelean.Hashes.SHA3.Tests
open RunTests Rsp

/-- Exercise the public bit API on bit-oriented fixtures. -/
def evaluateBits (variant : Nat) (m : Vector Bit n) : Array UInt8 :=
  let msg := BitVec.ofBitsLE m
  match variant with
    | 224 => ((sha3_224_bits msg).toBytesLE (n := 28)).toArray
    | 256 => ((sha3_256_bits msg).toBytesLE (n := 32)).toArray
    | 384 => ((sha3_384_bits msg).toBytesLE (n := 48)).toArray
    | _ => ((sha3_512_bits msg).toBytesLE (n := 64)).toArray

/-- Exercise the public byte API on byte-oriented fixtures. -/
private def evaluateBytes (variant : Nat) (m : Array UInt8) : Array UInt8 :=
  match variant with
    | 224 => (sha3_224 m.toVector).toArray
    | 256 => (sha3_256 m.toVector).toArray
    | 384 => (sha3_384 m.toVector).toArray
    | _ => (sha3_512 m.toVector).toArray

private def fixtureDir : System.FilePath := "Wychelean/Hashes/SHA3/Fixtures"

private def knownAnswers (dir file : String) (variant count : Nat)
    (byteOriented := true) : Suite where
  name := s!"{dir}/{file}"
  tests := do
    let vectors ← RunTests.Parser.parseFile
      (parseKat variant) (fixtureDir / dir / file)
    unless vectors.length == count do
      throw (IO.userError s!"{file}: expected {count} cases, got {vectors.length}")
    vectors.zipIdx.mapM fun (v, i) => do
      let actual ← if byteOriented then do
        unless v.msg.length % 8 == 0 && v.output.length % 8 == 0 do
          throw (IO.userError s!"{file}: byte-oriented case has a partial byte")
        pure (evaluateBytes variant v.msg.bytes)
      else pure (evaluateBits variant v.msg.bits)
      return check s!"{i}, Len={v.msg.length}, Outputlen={v.output.length}"
        (Hex.encode v.output.bytes) (Hex.encode actual)

/-- SHA3VS §6.2.3: 100 checkpoints of 1000 iterations each. -/
private def monte (dir file : String) (variant : Nat) : Suite where
  name := s!"{dir}/{file}"
  tests := do
    let data ← RunTests.Parser.parseFile (parseMonte variant) (fixtureDir / dir / file)
    let mut output := data.initial
    let mut tests := #[]
    for (expected, i) in data.outputs.zipIdx do
      for _ in [0:1000] do
        output := evaluateBytes variant output
      tests := tests.push (check s!"COUNT={i}" (Hex.encode expected.bytes) (Hex.encode output))
    return tests.toList

/-- Both NIST archives, unchanged; source links and counts are in the module comment. -/
def suites : List Suite := Id.run do
  let mut result := []
  for (byteOriented, counts) in
      [(true, [145,137,105,73]), (false, [1153,1089,833,577])] do
    let orientation := if byteOriented then "byte" else "bit"
    let dir := s!"sha-3{orientation}testvectors"
    for (variant, count) in [224,256,384,512].zip counts do
      let stem := s!"SHA3_{variant}"
      result := result ++ [knownAnswers dir (stem ++ "ShortMsg.rsp") variant count
          (byteOriented := byteOriented),
        knownAnswers dir (stem ++ "LongMsg.rsp") variant 100 (byteOriented := byteOriented),
        monte dir (stem ++ "Monte.rsp") variant]
  return result

end Wychelean.Hashes.SHA3.Tests
