import Wychelean.Hashes.Keccak.Basic

namespace Wychelean.Hashes.Keccak

/-- Table 2 (§3.2.2): precomputed ρ rotation offsets. -/
def ρOffsetsTable2 : Vector (Vector Nat 5) 5 := #v[
  #v[  0,  36,   3, 105, 210],
  #v[  1, 300,  10,  45,  66],
  #v[190,   6, 171,  15, 253],
  #v[ 28,  55, 153,  21, 120],
  #v[ 91, 276, 231, 136,  78]]

/-- Algorithm 2 matches Table 2 (§3.2.2). -/
theorem rhoOffsets_eq_table2 : ρ.Offsets = ρOffsetsTable2 := by native_decide



/-- Published round constants from the pinned XKCP Keccak-f[1600] trace:
https://github.com/XKCP/XKCP/blob/eb5244d6b95fb1c434b211bac293093e18aa8fd1/tests/TestVectors/KeccakF-1600-IntermediateValues.txt
Generated by FIPS 202 §3.2.5, Algorithms 5–6. -/
def roundConstants1600 : Vector (BitVec 64) 24 := #v[
  0x0000000000000001, 0x0000000000008082, 0x800000000000808A, 0x8000000080008000, 0x000000000000808B, 0x0000000080000001, 0x8000000080008081, 0x8000000000008009, 0x000000000000008A, 0x0000000000000088, 0x0000000080008009, 0x000000008000000A, 0x000000008000808B, 0x800000000000008B, 0x8000000000008089, 0x8000000000008003, 0x8000000000008002, 0x8000000000000080, 0x000000000000800A, 0x800000008000000A, 0x8000000080008081, 0x8000000000008080, 0x0000000080000001, 0x8000000080008008]

theorem roundConstants1600_eq :
    (Vector.ofFn fun (i : Fin 24) => ι.RC 6 i.val) = roundConstants1600 := by native_decide

/-- FIPS 202 §5.1 mandates both a leading and trailing one. -/
theorem padLen_ge_two (r n : Nat) : 2 ≤ padLen r n := by simp [padLen]

theorem pad_last (r n : Nat) : («pad10*1» r n)[padLen r n - 1]'(by simp [padLen]) = true := by
  unfold «pad10*1»
  change ((#v[true] ++ Vector.replicate (padLen.j r n) false) ++ #v[true])[padLen r n - 1] = true
  rw [Vector.getElem_append_right _ (by simp [padLen])]
  simp [padLen]

/-- Round offsets are computed in the integers, without saturating subtraction. -/
theorem roundIndex_first (ℓ : Width) (nr : Nat) :
    roundIndex ℓ nr 0 = 12 + 2 * (ℓ.val : Int) - nr := by simp [roundIndex]
theorem roundIndex_last (ℓ : Width) (nr : Nat) (h : 0 < nr) :
    roundIndex ℓ nr (nr - 1) = 11 + 2 * (ℓ.val : Int) := by unfold roundIndex; omega

end Wychelean.Hashes.Keccak
